<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="signin"
    errors="0" failures="1" hostname="" id="" package="signin" skipped="0"
    tests="1" time="6.307" timestamp="Mon, 04 Sep 2017 12:53:41 GMT">
  
    <testcase name="user sign in successful" classname="signin" time="6.307" assertions="2">

      <failure message="Testing if the URL equals &quot;http://localhost:9000/dashboard&quot;.">    at Object.userSignInSuccessful [as user sign in successful] (/Users/andeladeveloper/Dev/PostIt/tests/signin.js:13:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
